name: Fetch Telangana shows 1

on:
  schedule:
    - cron: '*/30 * * * *'  # every 30 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Batch1 fetch script
        run: node fetchShows.js

      - name: Commit and push CSVs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add output/*.csv
          if ! git diff --cached --quiet; then
            echo "🚀 CSV changes detected. Committing..."
            git commit -m "Update District shows CSVs [skip ci]"
            git pull --rebase origin main || true
            git push origin main
          else
            echo "⚠️ No CSV changes to commit."
