name: Fetch Shows Batch1

on:
  workflow_dispatch:   # Manual trigger (you can start it any time from GitHub Actions tab)

permissions:
  contents: write

jobs:
  run-batch1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install node-fetch@2

      - name: Run Batch1 Loop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          while true; do
            echo "🚀 Running Batch1 script..."
            node fetchShows.js

            echo "💾 Committing generated CSVs..."
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"

            git add output_*/*.csv

            if ! git diff --cached --quiet; then
              git commit -m "Update Batch1 CSVs [skip ci]"
              git pull --rebase origin main || true
              git push origin main
            else
              echo "⚠️ No CSV changes to commit."
            fi

            echo "✅ Finished run. Waiting 5 minutes before next run..."
            sleep 300
          done
