name: Fetch Shows Daily

on:
  schedule:
    - cron: '*/30 * * * *'  # every 30 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install node-fetch@2

      - name: Run fetchShows.js
        run: node fetchShows.js

      - name: Commit and push CSVs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add karnataka_show_wise_*.csv

          if ! git diff --cached --quiet; then
            git commit -m "Update Karnataka show CSVs [skip ci]"
          fi

          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/Cinemadata/Bms_Karnataka.git
          git pull --rebase origin main || true
          git push origin main
