name: Fetch Shows Daily

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Set date variable
        run: echo "DATE=$(date +%F)" >> $GITHUB_ENV

      - name: Run fetchShows.js
        run: node fetchShows.js

      - name: Commit and push CSVs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add output_${{ env.DATE }}

          if ! git diff --cached --quiet; then
            git commit -m "Update shows CSVs for ${{ env.DATE }} [skip ci]"
          fi

          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/Cinemadata/Bms_Karnataka.git
          git pull --rebase origin main || true
          git push origin main
