name: Fetch Tamil shows

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-and-push:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run your fetchTamil.js script
      - name: Run fetchTamil.js
        run: node fetchTamil.js

      # Step 5: Commit and push CSVs with conflict handling
      - name: Commit and push CSVs
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git pull origin main --rebase
          git add output/*.csv
          git commit -m "Update Tamil shows CSVs [skip ci]" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        
