name: Fetch Tamil shows

on:
  schedule:
    - cron: '*/30 * * * *'  # Every 30 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repository (use default credentials)
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run your fetch script
      - name: Run fetchTamil.js
        run: node fetchTamil.js

      # 5. Commit and push ONLY the CSVs
      - name: Commit and push CSVs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add output/*.csv

          # Only commit if there are changes
          if ! git diff --cached --quiet; then
            git commit -m "Update Tamil shows CSVs [skip ci]"
          fi

          git pull --rebase origin main
          git push origin main
