name: Fetch Tamil Showtimes

on:
  schedule:
    - cron: '*/30 * * * *'   # Runs every 30 minutes
  workflow_dispatch:          # Allows manual trigger from GitHub Actions UI

jobs:
  fetch-tamil:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Fetch Tamil Showtimes
        run: node fetchTamil.js

      - name: Commit and push CSVs
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add output/*.csv
          git commit -m "Update Tamil showtime CSVs [skip ci]" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
