name: Fetch Telugu shows

# Trigger every 30 minutes
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch: # manual trigger

# Give write permissions to push CSVs
permissions:
  contents: write

jobs:
  fetch-and-push:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run Telugu script
      - name: Run fetchTelugu.js
        run: node fetchTelugu.js

      
      # Commit and push generated CSVs
      - name: Commit and push CSVs
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add output/*.csv
          git commit -m "Update Telugu shows CSVs [skip ci]" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
