name: Fetch Telugu Shows

# Trigger every 30 minutes or manually
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

# Permissions for pushing CSVs
permissions:
  contents: write

jobs:
  fetch-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history to allow push

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Run Telugu show fetch script
      - name: Run fetchTelugu.js
        run: node fetchTelugu.js

      # 5️⃣ List generated CSVs for debugging
      - name: List CSVs
        run: ls -lh output/

      # 6️⃣ Commit and push CSVs safely (pull first)
      - name: Commit and push CSVs
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          # Pull latest changes from remote with rebase
          git pull origin main --rebase

          # Add CSVs and commit
          git add output/*.csv
          git commit -m "Update Telugu shows CSVs [skip ci]" || echo "No changes to commit"

          # Push updated branch
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
