name: Update Telugu Shows CSVs

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes

jobs:
  update-telugu-csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Pull latest changes from remote
        run: |
          git fetch origin main
          git reset --hard origin/main

      - name: Install dependencies
        run: npm install

      - name: Run Telugu.js
        run: node Telugu.js

      - name: Commit changes
        run: |
          git add .
          git commit -m "Update Telugu shows CSVs [skip ci]" || echo "No changes to commit"

      - name: Push changes
        run: git push origin main
