name: Fetch Telugu Showtimes

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  run-fetch-telugu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run fetchTelugu.js
        run: node fetchTelugu.js


      - name: Upload output CSVs
        uses: actions/upload-artifact@v4
        with:
          name: telugu-csvs
          path: output/*.csv

          
