name: Fetch Telugu shows

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: bms-karnataka-update
  cancel-in-progress: true

jobs:
  fetch-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository without persisting credentials
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run the script to fetch Telugu shows and append CSVs
      - name: Run fetchTelugu.js
        run: node fetchTelugu.js

      # Commit and push updated CSVs with retry logic and proper authentication
      - name: Commit and push CSVs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add output/*.csv
          if ! git diff --cached --quiet; then
            git commit -m "Update Telugu shows CSVs [skip ci]"
          fi
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/Cinemadata/Bms_Karnataka.git

          for i in 1 2 3; do
            git pull --rebase origin main && git push origin main && break
            echo "Push failed, retrying in 10 seconds..."
            sleep 10
          done
