name: Fetch Telugu Shows

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Get current date for output folder (YYYYMMDD)
      - name: Set date variable
        run: echo "DATE=$(date +%Y%m%d)" >> $GITHUB_ENV

      # Run the script to fetch Telugu shows
      - name: Run fetchTelugu.js
        run: node fetchTelugu.js

      # Commit and push updated CSVs
      - name: Commit and push CSVs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # Add today's output folder only
          git add output_${{ env.DATE }}

          # Commit if there are changes
          if ! git diff --cached --quiet; then
            git commit -m "Update Telugu shows CSVs for ${{ env.DATE }} [skip ci]"
          fi

          # Set remote URL to use the GitHub token for authentication
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/Cinemadata/Bms_Karnataka.git

          # Pull latest changes with rebase and push commits
          git pull --rebase origin main || true
          git push origin main
